In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Combined_News_DJIA.csv')
df.head()

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2  2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-14      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

In [3]:
train = df[df['Date'] < '20150101']
test = df[df['Date'] > '20141231']

In [4]:
data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

list1= [i for i in range(25)]
new_Index=[str(i) for i in list1]
data.columns= new_Index
data.head(5)

0  \
0  b Georgia  downs two Russian warplanes  as cou...   
1  b Why wont America and Nato help us  If they w...   
2  b Remember that adorable   year old who sang a...   
3  b  U S  refuses Israel weapons to attack Iran ...   
4  b All the experts admit that we should legalis...   

                                                   1  \
0            b BREAKING  Musharraf to be impeached     
1        b Bush puts foot down on Georgian conflict    
2                 b Russia  ends Georgia operation     
3  b When the president ordered to attack Tskhinv...   
4  b War in South Osetia      pictures made by a ...   

                                                   2  \
0  b Russia Today  Columns of troops roll into So...   
1  b Jewish Georgian minister  Thanks to Israeli ...   
2  b  If we had no sexual harassment we would hav...   
3  b  Israel clears troops who killed Reuters cam...   
4  b Swedish wrestler Ara Abrahamian throws away ...   

                                                   3  \
0  b Russian tanks are moving towards the capital...   
1  b Georgian army flees in disarray as Russians ...   
2  b Al Qa eda is losing support in Iraq because ...   
3  b Britain  s policy of being tough on drugs is...   
4  b Russia exaggerated the death toll in South O...   

                                                   4  \
0  b Afghan children raped with  impunity   U N  ...   
1      b Olympic opening ceremony fireworks  faked     
2  b Ceasefire in Georgia  Putin Outmaneuvers the...   
3  b Body of    year old found in trunk  Latest  ...   
4  b Missile That Killed   Inside Pakistan May Ha...   

                                                   5  \
0  b     Russian tanks have entered South Ossetia...   
1  b What were the Mossad with fraudulent New Zea...   
2  b Why Microsoft and Intel tried to kill the XO...   
3  b China has moved     million  quake survivors...   
4  b Rushdie Condemns Random House s Refusal to P...   

                                                   6  \
0  b Breaking  Georgia invades South Ossetia  Rus...   
1  b Russia angered by Israeli military sale to G...   
2  b Stratfor  The Russo Georgian War and the Bal...   
3  b Bush announces Operation Get All Up In Russi...   
4  b Poland and US agree to missle defense deal  ...   

                                                   7  \
0  b The  enemy combatent  trials are nothing but...   
1  b An American citizen living in S Ossetia blam...   
2  b I m Trying to Get a Sense of This Whole Geor...   
3             b Russian forces sink Georgian ships     
4  b Will the Russians conquer Tblisi  Bet on it ...   

                                                   8  \
0  b Georgian troops retreat from S  Osettain cap...   
1  b Welcome To World War IV  Now In High Definit...   
2  b The US military was surprised by the timing ...   
3  b The commander of a Navy air reconnaissance s...   
4  b Russia exaggerating South Ossetian death tol...   

                                                   9  ...  \
0  b Did the U S  Prep Georgia for War with Russia    ...   
1  b Georgia s move  a mistake of monumental prop...  ...   
2    b U S  Beats War Drum as Iran Dumps the Dollar   ...   
3  b     of CNN readers  Russia s actions in Geor...  ...   
4  b  Musharraf expected to resign rather than fa...  ...   

                                                  15  \
0  b Georgia Invades South Ossetia   if Russia ge...   
1  b Israel and the US behind the Georgian aggres...   
2  b U S  troops still in Georgia  did you know t...   
3                      b Elephants extinct by          
4  b Bank analyst forecast Georgian crisis   days...   

                                                  16  \
0                b Al Qaeda Faces Islamist Backlash    
1  b  Do not believe TV  neither Russian nor Geor...   
2       b Why Russias response to Georgia was right    
3  b US humanitarian missions soon in Georgia   i...   
4  b Georgia confict could set bac

In [5]:
for index in new_Index:
    data[index]=data[index].str.lower()
data.head(1)

0  \
0  b georgia  downs two russian warplanes  as cou...   

                                         1  \
0  b breaking  musharraf to be impeached     

                                                   2  \
0  b russia today  columns of troops roll into so...   

                                                   3  \
0  b russian tanks are moving towards the capital...   

                                                   4  \
0  b afghan children raped with  impunity   u n  ...   

                                                   5  \
0  b     russian tanks have entered south ossetia...   

                                                   6  \
0  b breaking  georgia invades south ossetia  rus...   

                                                   7  \
0  b the  enemy combatent  trials are nothing but...   

                                                   8  \
0  b georgian troops retreat from s  osettain cap...   

                                                   9  ...  \
0  b did the u s  prep georgia for war with russia    ...   

                                                  15  \
0  b georgia invades south ossetia   if russia ge...   

                                    16  \
0  b al qaeda faces islamist backlash    

                                                  17  \
0  b condoleezza rice   the us would not act to p...   

                                                  18  \
0  b this is a busy day   the european union has ...   

                                                  19  \
0  b georgia will withdraw       soldiers from ir...   

                                                  20  \
0  b why the pentagon thinks attacking iran is a ...   

                                                  21  \
0  b caucasus in crisis  georgia invades south os...   

                                                  22  \
0  b indian shoe manufactory    and again in a se...   

                                                  23  \
0  b visitors suffering from mental illnesses ban...   

                                         24  
0  b no help for mexico s kidnapping surge   

[1 rows x 25 columns]

In [6]:
headlines = []
for row in range(0,len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))

In [38]:
headlines[234:]

['b earthquake m    off west coast of south island new zealand   tsunami warning  b incredible  the israel project  a non profit with headquarters in d c   has issued a  global language dictionary   authored by republican pollster frank luntz  that tells journalists how to talk about the israel palestine conflict  newspeak much   b testimonies  an israeli sniper killed a palestinian  r nman in order to mark a score with his gun   r nsoldiers fired at houses out of boredom  a  r ncommander expressed satisfaction that gaza  r nhospitals were full   b  russian activist  found murdered   b israel drops charges against an israeli settler caught on film shooting at two palestinians in the west bank   reason  prosecution may result in harm israel s security   b israel soldiers speak out on gaza conflict  b israeli soldiers reveal the brutal truth of gaza  r nattack   b israeli soldiers admit widespread abuses were committed by the army against civilians during the assualt on gaza  b not only 

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [9]:
voc_size=100000

In [10]:
onehot_repr=[one_hot(words,voc_size)for words in headlines] 

In [11]:
sent_length=700
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[49253 42685 73123 ...     0     0     0]
 [49253 34973 78871 ...     0     0     0]
 [49253 69236 76299 ...     0     0     0]
 ...
 [20725  8317 27267 ...     0     0     0]
 [67369   487 19060 ...     0     0     0]
 [25184 41259 32552 ...     0     0     0]]


In [12]:
embedding_vector_features=100
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(500))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

C:\Users\h9773\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
import numpy as np

In [14]:
X=np.array(embedded_docs)
y=np.array(train['Label'])

In [39]:
X


array([[49253, 42685, 73123, ...,     0,     0,     0],
       [49253, 34973, 78871, ...,     0,     0,     0],
       [49253, 69236, 76299, ...,     0,     0,     0],
       ...,
       [20725,  8317, 27267, ...,     0,     0,     0],
       [67369,   487, 19060, ...,     0,     0,     0],
       [25184, 41259, 32552, ...,     0,     0,     0]])

In [16]:
y.shape

(1863,)

In [17]:
model.fit(X,y,epochs=20,batch_size=20)

Epoch 1/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 362s 4s/step - accuracy: 0.5565 - loss: 0.6892
Epoch 2/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 365s 4s/step - accuracy: 0.5299 - loss: 0.6919
Epoch 3/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 411s 4s/step - accuracy: 0.5395 - loss: 0.6911
Epoch 4/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 392s 4s/step - accuracy: 0.5328 - loss: 0.6914
Epoch 5/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 360s 4s/step - accuracy: 0.5197 - loss: 0.6932
Epoch 6/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 359s 4s/step - accuracy: 0.5278 - loss: 0.6921
Epoch 7/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 363s 4s/step - accuracy: 0.5215 - loss: 0.6924
Epoch 8/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 363s 4s/step - accuracy: 0.5299 - loss: 0.6915
Epoch 9/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 349s 4s/step - accuracy: 0.5387 - loss: 0.6907
Epoch 10/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 353s 4s/step - accuracy: 0.5280 - loss: 0.6916
Epoch 11/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 356s 4s/step - accuracy: 0.5568 - loss: 0.6877
Epoch 12/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 380s 4s/step - accuracy:

In [19]:
data_test=test.iloc[:,2:27]
data_test.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

list2= [i for i in range(25)]
new_Index_2=[str(i) for i in list2]
data_test.columns= new_Index_2
data_test.head(5)

0  \
1611  Most cases of cancer are the result of sheer b...   
1612  Moscow  gt Beijing high speed train will reduc...   
1613                    US oil falls below     a barrel   
1614                 Shots fired  at French magazine HQ   
1615  New Charlie Hebdo issue to come out next week ...   

                                                      1  \
1611  Iran dismissed United States efforts to fight ...   
1612  Two ancient tombs were discovered in Egypt on ...   
1613  Toyota gives away       fuel cell patents to b...   
1614        of Bibi Netanyahus Campaign Funds From U S    
1615  Ahmed Merabet  Cop Killed In Paris Attacks  Wa...   

                                                      2  \
1611  Poll  One in   Germans would join anti Muslim ...   
1612  China complains to Pyongyang after N Korean so...   
1613  Young Indian couple who had been granted polic...   
1614  ISIS behead street magician for entertaining c...   
1615  Youngest Suspect in Charlie Hebdo Attack Turns...   

                                                      3  \
1611  UK royal family s Prince Andrew named in US la...   
1612  Scotland Headed Towards Being Fossil Fuel Free...   
1613  A senior figure in Islamic States self declare...   
1614  Denmark sets new world record in renewable ene...   
1615  Grenades thrown at a mosque in Le Mans  west o...   

                                                      4  \
1611  Some    asylum seekers refused to leave the bu...   
1612  Prime Minister Shinzo Abe said Monday he will ...   
1613  Fukushima rice passes radiation tests for  st ...   
1614  ISIS Closes Schools In Syria  Leaving        C...   
1615  Danish newspaper to print Charlie Hebdo cartoo...   

                                                      5  \
1611  Pakistani boat blows self up after India navy ...   
1612  Sex slave at centre of Prince Andrew scandal f...   
1613  Nearly all Spanish parties guilty of financial...   
1614  The European Union wants Turkey to explain how...   
1615  Muslim politician from India offers   M to Cha...   

                                                      6  \
1611  Sweden hit by third mosque arson attack in a week   
1612  Gay relative of Hamas founder faces deportatio...   
1613             King Abdullah to abdicate Saudi Throne   
1614     people have died in a shooting at the headq...   
1615  Vladimir Putin has condemned a deadly terroris...   

                                                      7  \
1611             cars set alight during French New Year   
1612  The number of female drug addicts in Iran has ...   
1613    Taliban Commander Caught Networking On LinkedIn   
1614  Most Earth like planet ever discovered could b...   
1615  Turkey is trying to hide any evidence that hol...   

                                                      8  \
1611  Salaries for top CEOs rose twice as fast as av...   
1612  After Decades of Searching  the Causeway for t...   
1613  Mexican missing students  mayor s wife charged...   
1614  New questions raised about U S  Saudi relation...   
1615  Danish Paper That Published    Muhammad Cartoo...   

                                                      9  ...  \
1611  Norway violated equal pay law  judge says  Jud...  ...   
1612                       India lost    tigers in       ...   
1613  New York Times reporter James Risen refused on...  ...   
1614  Massive hunt underway for gunmen in Paris terr...  ...   
1615  Two Charlie Hebdo attackers located in north F...  ...   

                                                     15  \
1611  Ukrainian minister threatens TV channel with c...   
1612  The Islamic State has approved a      budget o...   
1613  Thousands of Indians have fled from their home...   
1614  Discovery of witnesss mutilated body feeds cla...   
1615  Thousands in Europe hold up Pens in Solidarity...   

                                                     16  \
1611  Palestinian President Mahmoud Abbas has entere...   
1

In [21]:
for index in new_Index_2:
    data_test[index]=data_test[index].str.lower()


In [23]:
headlines_test = []
for row in range(0,len(data_test.index)):
    headlines_test.append(' '.join(str(x) for x in data_test.iloc[row,0:25]))

In [25]:
onehot_repr_test=[one_hot(words,voc_size)for words in headlines_test] 

In [27]:
sent_length=700
embedded_docs_text=pad_sequences(onehot_repr_test,padding='post',maxlen=sent_length)
print(embedded_docs)

[[49253 42685 73123 ...     0     0     0]
 [49253 34973 78871 ...     0     0     0]
 [49253 69236 76299 ...     0     0     0]
 ...
 [20725  8317 27267 ...     0     0     0]
 [67369   487 19060 ...     0     0     0]
 [25184 41259 32552 ...     0     0     0]]


In [29]:
X_test=np.array(embedded_docs_text)
y_test=test['Label']

In [31]:
y_pred=model.predict(X_test)

12/12 ━━━━━━━━━━━━━━━━━━━━ 12s 997ms/step


In [33]:
y_pred=np.where(y_pred > 0.5, 1,0)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y_test,y_pred)

array([[  0, 186],
       [  0, 192]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5079365079365079

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       186
           1       0.51      1.00      0.67       192

    accuracy                           0.51       378
   macro avg       0.25      0.50      0.34       378
weighted avg       0.26      0.51      0.34       378



C:\Users\h9773\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\h9773\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\h9773\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
